FROM jenkins/jenkins:lts
USER root

# Install dependencies for MLOps pipelines
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    bc \
    docker.io && \
    apt-get clean

USER jenkins